### Get JWT Tokens
POST http://localhost:8000/api/token/
Content-Type: application/json

{
    "email": "mohamed.aziz.ali@outlook.com",
    "password": "123"
}
### Refresh JWT Token
POST http://localhost:8000/api/token/refresh/
Content-Type: application/json

{
    "refresh": "your_refresh_token"
}