# Generated by Django 5.2 on 2025-05-02 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='disease_type',
            field=models.CharField(choices=[('No Finding', 'No Finding'), ('Pneumonia', 'Pneumonia'), ('Pneumothorax', 'Pneumothorax'), ('Effusion', 'Effusion'), ('Cardiomegaly', 'Cardiomegaly')], default=django.utils.timezone.now, help_text='Diagnosis result from ML model', max_length=50),
            preserve_default=False,
        ),
    ]
