# Generated by Django 5.2 on 2025-04-26 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('pneumonia', 'Pneumonia'), ('lung_opacity', 'Lung opacity'), ('pneumothorax', 'Pneumothorax'), ('pleural_effusion', 'Pleural effusion'), ('unknown', 'Unknown'), ('normal', 'Normal')], help_text='Diagnosis result from ML model', max_length=50)),
                ('diagnosed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-diagnosed_at'],
            },
        ),
    ]
