# Generated by Django 5.2 on 2025-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='disease_type',
            field=models.CharField(choices=[('0', 'No Finding'), ('1', 'Pneumonia'), ('2', 'Pneumothorax'), ('3', 'Effusion'), ('4', 'Cardiomegaly')], help_text='Diagnosis result from ML model', max_length=50),
        ),
    ]
