# Generated by Django 5.2 on 2025-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0003_alter_diagnosis_disease_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='disease_type',
            field=models.CharField(choices=[('No Finding', 'No Finding'), ('Pneumonia', 'Pneumonia'), ('Pneumothorax', 'Pneumothorax'), ('Effusion', 'Effusion'), ('Cardiomegaly', 'Cardiomegaly')], help_text='Diagnosis result from ML model', max_length=50),
        ),
    ]
